### PR TITLE
Update pagination.eml possible fix to #1728

### LINKED ISSUE #1728: pagination on package search result page shows  extra "1" when result fits into one page
[screen-capture.webm](https://github.com/ocaml/ocaml.org/assets/70571088/43376f30-b236-4329-a341-76006d456abd)

### PR DESCRIPTION
**Pull request by AndroGenius-codes**
Resolves #1728

@sabine @SaySayo  i made a simple ui fix to the pagination function. its a possible fix to the previous issue i opened #1728 
[screen-capture (1).webm](https://github.com/ocaml/ocaml.org/assets/70571088/2ca42cf7-2914-420b-ab83-b8b84d2783f7)

### CODE REVIEW

**Comment by sabine** [comment]
That you saw this and tried to make a fix is great @AndroGenius-codes! :heart: 

I noticed one thing, though:

When there's only a single page, I think we do not need to render pagination at all.

So the simple and clean solution here looks to be to make one big `if then else` statement on `total_page_count > 1` to decide whether to render the pagination.

**Comment by AndroGenius-codes** [comment]
> That you saw this and tried to make a fix is great @AndroGenius-codes! ❤️
> 
> I noticed one thing, though:
> 
> When there's only a single page, I think we do not need to render pagination at all.
> 
> So the simple and clean solution here looks to be to make one big `if then else` statement on `total_page_count > 1` to decide whether to render the pagination.

Makes sense. Let me do that

**Comment by AndroGenius-codes** [comment]
> That you saw this and tried to make a fix is great @AndroGenius-codes! ❤️
> 
> I noticed one thing, though:
> 
> When there's only a single page, I think we do not need to render pagination at all.
> 
> So the simple and clean solution here looks to be to make one big `if then else` statement on `total_page_count > 1` to decide whether to render the pagination.

Thank you for the feedback, the new commit accomplishes this.

**Comment by AndroGenius-codes** [comment]
[screen-capture (2).webm](https://github.com/ocaml/ocaml.org/assets/70571088/cc9259e1-1a81-4e36-8123-0f7fdbe5d5f0)
new appearance of pagination feature

**Review by sabine — APPROVED** [review]
Thanks @AndroGenius-codes! LGTM

**Comment by AndroGenius-codes** [comment]
> Thanks @AndroGenius-codes! LGTM

Thank you too

**Pull request merged**
