### PR TITLE
implement darkmode on Learn/Excercise page

### PR DESCRIPTION
**Pull request by oyenuga17**
@Sayo @Puchangan please help review

### CODE REVIEW

**Review by SaySayo — APPROVED** [review]

**Comment by SaySayo** [comment]
This looks good to me! I think it's ready for a final review. cc @sabine

**Review by sabine — COMMENTED** [review]
Screenshot 2024-01-10 at 13-14-56 Exercises

Exercises side navigation color looks wrong to me on first glance. Haven't checked with the Figma design, though.

Footer navigation also looks incomplete on first glance:
Screenshot 2024-01-10 at 13-15-12 Exercises

**Comment by sabine** [comment]
The reason I'm pointing these out is that it's hard for @Clairevanden to review the entire page when parts of the dark mode on it are unimplemented.

**Comment by oyenuga17** [comment]
My eyes the skipped Exercises side navigation, I only just realized 😩 but for the Footer navigation I need to rebase [this pr](https://github.com/ocaml/ocaml.org/pull/1896) . Thank you i will get to it

**Comment by sabine** [comment]
It's probably easier to not open so many PRs at the same time because of all the rebasing on shared component changes. It's okay if the individual PRs do more.

**Comment by oyenuga17** [comment]
Okay, thank you @sabine. I think I'll go ahead and change the dependent pr's to draft for now. For subsequent pr's, I'll create them one after the other

**Pull request closed without merging**
