### PR TITLE
fork river

### PR DESCRIPTION
**Pull request by cuihtlauac**
- Bringup peter-evans/create-pull-request to v5
- Pin opam repo in scrape
- Use forked river

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks @cuihtlauac! Can you open a PR in https://github.com/kayceesrk/river instead to avoid forking? Generally, we should try to reduce the number of forks we have and this one is easy: I have commit right to river.

**Comment by sabine** [comment]
In an ideal world, the timeout in river would be configurable. Though, I think there will still be cases where timeouts will inevitably happen - sometimes the other website may just be offline while we scrape. So our scraper must gracefully recover from that and proceed to scrape the remaining sites.

**Comment by cuihtlauac** [comment]
For sure I will open a pr on river as soon as I have a patch. The fork is an interim thing allowing me to debug issues in ci.

**Comment by cuihtlauac** [comment]
Here is a quickfix PR: https://github.com/kayceesrk/river/pull/9 
A longer-term solution remains required.
I will revert this PR.

**Pull request merged**
