### PR TITLE
removed packages-home.png

### LINKED ISSUE #1890: Hide "OCaml Packages" Image on Homepage on Mobile View
Dear maintainers,
First of all, thanks for your hard work on making the OCaml ecosystem available for everyone 
👐

This issue is just to point out that there is a display problem with the image bellow the OCaml Package Explore link. The image appears to be right shift.

Here is two screenshots to show the issue on both Chromium and Firefox mobile :

Hope it helps 😇

### PR DESCRIPTION
**Pull request by The-Amoghavarsha**

### CODE REVIEW

**Review by sabine — COMMENTED** [review]
hey @The-Amoghavarsha, this is great except for one thing: the diff is very very large. It's very hard to see what the actual change is.

It would be super helpful to change this to have the smallest possible diff.

**Comment by The-Amoghavarsha** [comment]
> hey @The-Amoghavarsha, this is great except for one thing: the diff is very very large. It's very hard to see what the actual change is.
> 
> It would be super helpful to change this to have the smallest possible diff.

Hey @sabine, sorry for the mess. Did that with someone else's computer. I see the problem. It has to do something with the `core.autocrlf setting` set to true. Furthermore, I'll try to fix it, or I'll make another PR. :/

**Comment by sabine** [comment]
You can force push this PR or open another one. And yeah, this happens. We're lucky it's just a small patch, so not too much effort to start from the main branch and add the changes. :slightly_smiling_face:

**Comment by The-Amoghavarsha** [comment]
> You can force push this PR or open another one. And yeah, this happens. We're lucky it's just a small patch, so not too much effort to start from the main branch and add the changes. 🙂

Well, rebasing and force pushing is an option, but I think it's too late now. So, making another PR :'''''/

**Pull request closed without merging**
