### PR TITLE
couple of redirection added

### PR DESCRIPTION
**Pull request by rgrupesh**
related to #104 

Couple of fixes

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks @rgrupesh!

Looks like a good start, I think the releases redirections should be relatively easy to add as well. I'll check for the others to give you some pointers 🙂 

Could you also revert the removal of the `package-lock.json` file?

**Comment by rgrupesh** [comment]
@tmattio Do I need to write `release` function to route those releases Urls? Can it be routed using relative path? How should I go about this?

**Comment by tmattio** [comment]
@rgrupesh To give an example, this redirection: https://github.com/ocaml/v3.ocaml.org-server/blob/main/src/ocamlorg_web/lib/redirection.ml#L2 (which is this page on the current ocaml.org: https://ocaml.org/releases/4.05.html) can redirect to `/releases/4.05.0` (this page on v3: https://v3.ocaml.org/releases/4.05.0).
And the same mapping can be done for every release.

**Comment by rgrupesh** [comment]
@tmattio I am still working on this. Just to let you know, we have festival season going on that is why I was inactive lately. I will be committing fully to this PR after couple of days.

Besides, when I try to add releases URL like this:



I get this error message:



To achieve routing like above, do I need to write function like `tutorial` in `page_handler.ml`. Or, there is another way around?

P.S: I am newbie to this ecosystem. I am learning while contributing. I hope you understand.

**Comment by gs0510** [comment]
@rgrupesh If you look at the error message, it tells you that the expression `Url.releases` has a type string, which is why you can't pass a string parameter to it. You need to write a function so that it can take a string parameter which can redirect the users to the correct link. :)

**Comment by rgrupesh** [comment]
@gs0510 I didn't find any `.md` files related to the `/community`. Are those routes available? Or, should I redirect all of those paths to the `/`?

**Comment by tmattio** [comment]
Thanks a lot for all the work @rgrupesh! I've added a few missing redirections in addition to the one you added, this is now good to be merged 🙂

**Comment by rgrupesh** [comment]
> Thanks a lot for all the work @rgrupesh! I've added a few missing redirections in addition to the one you added, this is now good to be merged slightly_smiling_face

Thanks to you @tmattio . I learned a lot about the project structure and code base under your supervision.

**Pull request merged**
