### PR TITLE
Add changelog for infra upgrade to Debian 12

### PR DESCRIPTION
**Pull request by rikusilvola**
Crossposting from [infra blog](http://infra.ocaml.org/2023/06/28/upgrading-linux-distros.html)

cc: @tmattio @tmcgilchrist

### CODE REVIEW

**Comment by tmattio** [comment]
This LGTM, did you want to change anything before merging (seeing you open the PR as a draft)?

**Comment by rikusilvola** [comment]
Good for me. Any comments @tmcgilchrist ? I've changed the title slightly and added changelog entries vs the original.

**Comment by rikusilvola** [comment]
@tmattio ready to merge

**Review by tmcgilchrist — APPROVED** [review]

**Comment by tmattio** [comment]
Thank you!

**Comment by rikusilvola** [comment]
Slight issue with numerous tags 
image

**Pull request merged**
