### PR TITLE
Implement Academic Page Redesign

### PR DESCRIPTION
**Pull request by oyenuga17**
@sabine please help put on staging 🙏

### CODE REVIEW

**Review by christinerose — APPROVED** [review]

**Comment by cuihtlauac** [comment]
Something strange is taking place with this PR.

CI attempts to build commit 7be9c3492f35555573af6d687205dc1d870c592a (see Checks / Build and test (ubuntu-latest) / Checkout Repo / Fetching the repository). Under that commit, I see the same issue as in the checks.

However, doing `gh pr checkout 2694` switches to commit 8fcd29a3c812d1ec8b0e2c29ed97e50c1e260a5f (which is the latest pushed on the PR commits lists). There, the compilation has no errors.

**Comment by cuihtlauac** [comment]
I better understand what's going on. Check the "Checkout Repo" part of the CI build log. Line 73 says:
```
HEAD is now at 72e1a29 Merge f277dd95d9e2c1210e2c2c95a4399163eba4acd4 into 39a5d167292a6fdcc1a6644ec10808e4f5eeec96
```
f277dd95d9e2c1210e2c2c95a4399163eba4acd4: this is the latest commit of your branch
39a5d167292a6fdcc1a6644ec10808e4f5eeec96: this main right after merging PR #2698 

You can reproduce the CI build error by doing this:
```shell
git checkout -b merge-2694 39a5d167292a6fdcc1a6644ec10808e4f5eeec96
git merge f277dd95d9e2c1210e2c2c95a4399163eba4acd4
make build
```

There's a sync issue between your branch and main. Doing `git rebase main` in your branch also allows to reproduce the build failure

**Comment by oyenuga17** [comment]
@cuihtlauac thanks for pointing this out. I'll make the necessary update 👍

**Review by christinerose — APPROVED** [review]

**Review by christinerose — APPROVED** [review]

**Review by sabine — APPROVED** [review]
Thanks @oyenuga17, this is great!

**Pull request merged**
