### PR TITLE
eddited project

### PR DESCRIPTION
**Pull request by oabdulhamid1**
This is my OCaml Refactor Location contribution

### CODE REVIEW

**Comment by patricoferris** [comment]
Thanks @oabdulhamid1 for the PR !

You seem to have added this project as submodule of itself which is stopping the CI from being able to clone the project (see: https://deploy.ci3.ocamllabs.io/job/2021-10-22/135519-ocluster-build-f0580e). I'm guessing that might have been by accident when using git? We'll need to remove that :))

Secondly your change to `academic_institution.ml` doesn't compile for a couple of reasons. Mainly, the `metadata` type still references the old type `location` which no longer exists. On my machine the project won't compile because of this. 

```
File "tool/ood-gen/lib/academic_institution.ml", line 23, characters 15-23:
23 |   ; location : location option
                    ^^^^^^^^
Error: Unbound type constructor location
Hint: Did you mean option?
```

Do you have the project setup locally? Did you manage to get it to build?

**Comment by oabdulhamid1** [comment]
Hi,

I'm couldn't get to build the first one I did because some packages failed
to install, so I had to start again and I'm stuck at another point now.

Kindly help looks into the picture attached and help suggest a solution.

Regards.

**Comment by tmattio** [comment]
Thanks for the PR @oabdulhamid1! We're asking applicants to set up their project first, before starting on an issue (you'll need to be able to build to make sure the changes you made are correct). I'm going to suggest that you seek help on Discord if you have trouble setting up the project (I'm on the channel, so if you can upload your screenshot there, I'll be able to help), and come back to the PR once you're up and running. I'm closing the PR in the meantime, but let's reopen when you're ready 🙂

**Comment by oabdulhamid1** [comment]
Thanks @Thibaut Mattio ***@***.***>  will do that and revert
as soon as possible.

**Pull request closed without merging**
