### PR TITLE
Introduce a tools section for platform page, releases page, and a news section for changelog, OCaml Planet and Newsletters

### LINKED ISSUE #1985: Documenting the compiler release cycle?
I am wondering if it would be a good idea to document the current release cycle of the compiler on ocaml.org?

I have the impression that it could be useful to at least write down that:

* the compiler follows a linux-like semantics for version numbers `major.minor.patch` where both minor and major version may contain breaking changes. 
* the compiler is released approximately every 6 months
* Three months before the release of a new version, the set of new features is frozen.
* Pre-release version(alpha, beta, rcs) of the compiler are published two to three months before the release in order to test this new version.

Such page could be also a good place to link to compiler repository and its `CONTRIBUTING.md` rather than having a small link in the footer.

Any opinion on this idea?

### PR DESCRIPTION
**Pull request by sabine**
I propose to restructure the site such that there is a dedicated Tools section in the top level navigation.

This patch
* restructures the site to introduce a "Tools" section which currently contains the Platform Tools page and the Compiler Releases page.
* splits the Platform section that previously existed in the Learn area into a part that lives in the new Tools section (the Platform page, as well as the accompanying non-learning-related documents), and the tutorials which stay within the Learn area. To achieve this, a new `data/` kind `tool_page` has been added.
* adds text on the Platform page to give more context about the lifecycle of the Platform Tools and moves the video to the bottom of the page
* as a consequence of this restructuring, the non-learning-related Platform Tools documents no longer show up in the search results of the Learn area search
* in the Platform section of the Learn area, we now use categories to separate the different tutorials by topic, instead of listing them all under "Best Practices"
* Compiler Releases and Platform Tools pages are now discoverable through the top level navigation
* Redirects for the moved Platform pages are set up
* Changelog, OCaml Planet, and Newsletters page now live under a "News" area
* Resolves https://github.com/ocaml/ocaml.org/issues/1985 by adding a new page "The Compiler Release Cycle"

|page|before|after|
|-|-|-|
|Platform Section of the Learn Area|Screenshot 2024-05-06 at 22-52-03 OCaml Platform|Screenshot 2024-05-06 at 22-53-15 Bootstrapping a Project · OCaml Documentation|
|Platform Tools|Screenshot 2024-05-17 at 18-33-51 OCaml Platform|Screenshot 2024-05-17 at 18-33-55 OCaml Platform|
|Top level nav News/Blog|Screenshot 2024-05-15 at 17-35-37 OCaml Blog|Screenshot 2024-05-15 at 17-35-42 OCaml Changelog|
|OCaml Planet|Screenshot 2024-05-15 at 17-35-37 OCaml Blog|Screenshot 2024-05-15 at 17-35-46 The OCaml Planet

### CODE REVIEW

**Comment by sabine** [comment]
Additional remark:

This could also be the place where a "Compiler" page could be introduced that explains the different targets and the tiers, and such.

**Review by christinerose — APPROVED** [review]

**Review by tmattio — APPROVED** [review]
Looks like a very clear improvement to me!

The only nitpick I have is to keep the Playground/Play terminology, as I suspect the OCaml Playground has become something that people talk about in those terms.

**Comment by cuihtlauac** [comment]
Regarding the `https://ocaml.org/blog` page, you are removing the news thing (on the right). Where is this content going?

**Comment by sabine** [comment]
This is at the Newsletters subnav.

I think we could use a news overview page that provides a window into all the feeds the site has.

**Comment by sabine** [comment]
@tmattio "Play" will fit, but "Playground" takes to much space unless we can make the "Get Started" button smaller.

**Comment by cuihtlauac** [comment]
> @tmattio "Play" will fit, but "Playground" takes to much space unless we can make the "Get Started" button smaller.

Why not “Start” and “Play” ?

**Comment by cuihtlauac** [comment]
> This is at the Newsletters subnav.
> 
> I think we could use a news overview page that provides a window into all the feeds the site has.

News also includes stuff like this:
* https://ocaml.org/news/invitation-to-contribute
* https://ocaml.org/news/sigplan_announcement
* https://ocaml.org/news/2023-05-30-emissions-monitoring

Does it fit into “Newsletters”?

**Review by christinerose — APPROVED** [review]

**Comment by sabine** [comment]
> News also includes stuff like this:
> 
>     * https://ocaml.org/news/invitation-to-contribute
> 
>     * https://ocaml.org/news/sigplan_announcement
> 
>     * https://ocaml.org/news/2023-05-30-emissions-monitoring
> 
> 
> Does it fit into “Newsletters”?

I think it does.

**Review by christinerose — APPROVED** [review]

**Comment by sabine** [comment]
I'm merging because I received no pushback in conversations I had about this, and because it will enable us to place a banner or other announcement for the Dune Developer Preview in a location that can be discovered from the main navbar.

Further refinement / rearrangement is still possible.

**Pull request merged**
