### PR TITLE
Remove references to the platform installer

### PR DESCRIPTION
**Pull request by cuihtlauac**
- Text in /docs/platform
- Url and routes

### CODE REVIEW

**Comment by panglesd** [comment]
Just to satisfy my curiosity, what are the main reasons to remove those references?

**Comment by cuihtlauac** [comment]
Sorry, this PR should been a draft. What are the plans regarding the installer?

**Comment by tmattio** [comment]
With the ongoing work to add package management to Dune, which will make Dune the recommended tool for people to build projects, the way to get started and install developer tools will change. In the meantime, the recommended way is to install them manually with opam, and the easiest (but unofficial) way still seems to be to use the Platform installer, so the documentation seems correct. 

I initially thought that in light of the above, we shoul keep the documentation as-is, but:
- Since ocaml-platform-installer is being less maintained (as a result of very few opened issues, but I don't think we plan to spend a lot of time on the tool in the future given the focus on Dune 4)
- We've had a very high bar for what gets into the official docs so as to keep OCaml.org unbiased, and while ocaml-platform-installer is a great tool, I'm not sure it meets the standards we've applied to other tools
- There seem to be very few users of the tool, despite Tarides advertising for it

I would suggest that we go through with that PR. Does that sound good to you @panglesd? I know we discussed the opposite a few days ago.

**Comment by panglesd** [comment]
That sounds good to me! I think ocaml.org being unbiased is an important goal, and the installer has not being through any process to enter the platform tools.

It had its chance, being in the official doc for some time, but did not gain much attention, so I also think going on with this PR won't change the user experience a lot when installing OCaml.

**Review by sabine — APPROVED** [review]
Alright, then let's merge.

**Pull request merged**
