### PR TITLE
Turned exercise 013 into practice

### PR DESCRIPTION
**Pull request by divyankachaudhari**
Addresses #2198. Turns [Exercise 13](https://github.com/divyankachaudhari/ocaml.org/blob/010/data/exercises/013_run_decoding_direct.md) into Practice.

`dune build --root .` works.

@cuihtlauac Can you please review this? Thank you

----
Addresses all potential issues pointed out at #2179.

Closed earlier #2202 due to issues on my end.

### CODE REVIEW

**Comment by cuihtlauac** [comment]
The answer provided in the initial markdown needs to be corrected.
```ocaml
encode ["d"; "e"; "e"]
```
returns `[One "d"; Many (3, "e")]` which is one off on `"e"`.

Can you fix it too?

**Review by cuihtlauac — CHANGES_REQUESTED** [review]
Function `encode` has a bug, it must be fixed

**Comment by divyankachaudhari** [comment]
> The answer provided in the initial markdown needs to be corrected.
> 
> ```ocaml
> encode ["d"; "e"; "e"]
> ```
> 
> returns `[One "d"; Many (3, "e")]` which is one off on `"e"`.
> 
> Can you fix it too?

@cuihtlauac There's no such example in the [initial markdown](https://github.com/divyankachaudhari/ocaml.org/blob/010/data/exercises/013_run_decoding_direct.md). There's only one example. Can you clarify?

There's only this example:
```
# encode ["a";"a";"a";"a";"b";"c";"c";"a";"a";"d";"e";"e";"e";"e"];;
- : string rle list =
[Many (4, "a"); One "b"; Many (2, "c"); Many (2, "a"); One "d";
 Many (4, "e")]
 ```

**Review by cuihtlauac — APPROVED** [review]
Looks good to me. Thanks @divyankachaudhari

**Pull request merged**
