### PR TITLE
(staging only) Add dark mode script

### PR DESCRIPTION
**Pull request by oyenuga17**
@sabine I added the dark-mode script here, and we can temporarily test it by adding this script below to the browser console pending when the button is created 
**add** `document.documentElement.classList.add('dark')`
**remove** `document.documentElement.classList.remove('dark')`

### CODE REVIEW

**Comment by sabine** [comment]
Can you have only the dark mode script in this PR? It seems to contain all the other commits from the other PR as well.

You might be able to `git rebase -i` and keep only the dark mode script commit, or reset the branch to `main` and then add only a single commit with the dark mode script.

**Comment by oyenuga17** [comment]
Hi @sabine i am not sure how to do `git rebase -i` but i tried to reset this branch to main but it is not working. Maybe i should just close this pull request and create another branch

**Comment by sabine** [comment]
`git rebase -i main` gives you a list of commits that you can edit. Removing all the unrelated ones.

**Comment by oyenuga17** [comment]
> `git rebase -i main` gives you a list of commits that you can edit. Removing all the unrelated ones.

okay let me try this

**Pull request closed without merging**
