### PR TITLE
Add a New OCaml playground tutorial

### PR DESCRIPTION
**Pull request by The-Amoghavarsha**
Hey, as per issue #1853, I've added a tiny, yet detailed tutorial on how to use OCaml playground.

### CODE REVIEW

**Comment by sabine** [comment]
Thanks, this is super helpful! 😍 Will have a closer look probably next week.

The only thing I see on first glance is that it would be good to rebase on main, so that it's only the commit that adds the playground tutorial.

**Review by christinerose — COMMENTED** [review]
Approved on my end thus far, but it will need to be reviewed/approved by @cuihtlauac and/or @sabine for content.

**Review by sabine — APPROVED** [review]
I did some light editing and clarified `;;` behavior. Thank @The-Amoghavarsha! This is a great contribution. :heart:

LGTM

**Comment by The-Amoghavarsha** [comment]
> I did some light editing and clarified `;;` behavior. Thank @The-Amoghavarsha! This is a great contribution. ❤️
> 
> LGTM

Thanks. Glad it worked out. Do you want me to add something else (extra)?

**Comment by sabine** [comment]
I couldn't think of anything. I just forgot to merge when I got distracted waiting for the CI!

**Comment by The-Amoghavarsha** [comment]
> I couldn't think of anything. I just forgot to merge when I got distracted waiting for the CI!

Oh got it. Good night. 🌌

**Pull request merged**
