### PR TITLE
Fix: horizontal scrolling on the Ocaml ecosystem section

### PR DESCRIPTION
**Pull request by FatumaA**
This PR fixes this issue #819.
It:
1. removes the swiper as it is no longer needed
2. displays the cards in a single column on small screens and in 2 columns on mid sized screens
3. uses the pre-existing package_card function to render the cards
4. removes unnecessary tailwind classes and extra unused markup
5. add padding on x axis on mobile screens
6. improves alignment within the card containing the package image and description

Attached a screenshot of the results below:
Screenshot 2023-10-12 at 14 53 23
Screenshot 2023-10-12 at 14 53 41

Notes for improvements:
- perhaps we can have the list of packages interated through instead of repeating the markup/code below: 
`<%s! package_card
      ~href:"https://mirage.io/"
      ~img_path:"img/home/mirage.png"
      ~name:"MirageOS"
      "Library operating system to construct unikernels" %>`

### CODE REVIEW

**Comment by FatumaA** [comment]
@SaySayo  this is ready for review

**Comment by sabine** [comment]
@FatumaA

I see two problems with this solution:

1. Alignment issue on `sm` screen width:
Screenshot 2023-10-12 at 18-10-55 Welcome to a World of OCaml

2. Cards appearing squashed at smallest `md` screen width:
Screenshot 2023-10-12 at 18-10-31 Welcome to a World of OCaml

I really like the two column and single column layout on the small screens. This is going to work out fine. For the `md` screen, it seems trickier to find a good display that doesn't require the horizontal scroll.

**Comment by FatumaA** [comment]
The alignment is fixed now @sabine.

As for the squishy, not sure if there is another way other than to have the card contents vertical. Such that the image is on top of the text, giving the text more room. Or to reduce the number of cards visible at that breakpoint. But I think it looks a little bit better with the reduced padding as in here:


https://github.com/ocaml/ocaml.org/assets/67555014/abed2480-7b82-4358-8ab0-2161c0f10449

**Comment by sabine** [comment]
Looking much better!

There's only two ideas I have to make it another litttle bit better:

1. on screen below `md`: Introduce a maximum-width to keep the cards constrained to a width where they do not look as empty. This is what I see now:
Screenshot 2023-10-16 at 10-13-48 Welcome to a World of OCaml

2. Regarding the squishing at `lg` screen: reduce horizontal padding on `lg` screen and introduce the regular amount of padding on `xl` screen.

**Comment by FatumaA** [comment]
do you mean reducing the padding within the card or its parent?

**Comment by sabine** [comment]
> do you mean reducing the padding within the card or its parent?

I mean the container padding. But there's room to experiment.

**Comment by FatumaA** [comment]
I think you can retest it. 

It seems acceptable to me but at the moment, I don't have access to an xl screen to test with.

**Comment by sabine** [comment]
Much better!

For large screens, here's a screenshot:

Screenshot 2023-10-17 at 09-23-38 Welcome to a World of OCaml

You can use the browser zoom feature to scale the page to get an impression how it would look like on a bigger screen.

You still need to use the container so that the maximum width is constrained.

**Comment by FatumaA** [comment]
I moved the div containing the grid card into container-fluid div. And adjusted that class in styles.css to include a max width for small screens. 

Screenshots for clarity below:

Screenshot 2023-10-17 at 12 41 03
Screenshot 2023-10-17 at 12 43 41
Screenshot 2023-10-17 at 12 43 52

**Comment by sabine** [comment]
Wonderful, looks great to me! Thanks so much for the contribution @FatumaA!

**Review by sabine — COMMENTED** [review]
Now there's only one thing to do: cleaning up the PR so it only changes `home.eml`.

I think some merges you did introduced commits to the PR that shouldn't be here. Merge commits often introduce this problem. When working with a feature branch, it is often safer to rebase on the `main` branch, instead of doing merge commits. (Rebasing a branch takes the commits on that branch and tries to apply them one by one to the new state of the branch you're rebasing on.)

In this case, I think the simplest way to recover would be to copy the part of `home.eml` that you modified, and to reset the branch on `main`, then commit just the changes you made to `home.eml.

**Comment by FatumaA** [comment]
Changes on style.css are important for this fix. 

What if i revert the changes i merged into this branch from main?

**Comment by sabine** [comment]
Yes, so whatever you do to get to a PR that has only the necessary changes... do make sure you don't lose your changes. :slightly_smiling_face:

**Comment by FatumaA** [comment]
This got super confusing for me. 
I went ahead and opened a new PR with just my (cherry-picked) changes here: #1668 

I hope this is acceptable.

**Comment by sabine** [comment]
@FatumaA that's a perfectly fine solution. I'm closing this PR in favor of #1668

**Pull request closed without merging**
