### PR TITLE
Feat/events rss feed

### LINKED ISSUE #2392: Publish an RSS feed for Events
Similar to the OCaml Changelog, Events should be provided as a RSS feed (so that we can connect them with social media accounts on Twitter, LinkedIn, and Mastodon).

Hints:
- Look at the implementation of RSS feeds for the OCaml Changelog (https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/changelog.ml) as inspiration for how to do this for Events (https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/lib/event.ml).
- The `create_feed` function for Events needs to be registered as a sub-command of `ood-gen` here: https://github.com/ocaml/ocaml.org/blob/main/tool/ood-gen/bin/gen.ml
- You need to add a dune rule at https://github.com/ocaml/ocaml.org/blob/main/dune that runs the `ood-gen` tool to create the `.xml` file.
- Update the template at `events.eml` to add a link to the RSS feed.

### PR DESCRIPTION
**Pull request by ishar19**
Resolves #2392

### CODE REVIEW

**Review by sabine — COMMENTED** [review]
Hey @ishar19, this looks awesome! :sparkles: 

Here's some things to consider to make this useful for posting updates to social media, and to be useful in RSS readers:
- the start date of the event should be included in its title
- instead of using the summary element to hold the location, I would instead use the content element to render the same information that is listed on the event card. Summary element can be omitted.
- we cannot use the URL to the actual event as atom:id: "The content of an atom:id element MUST be created in a way that assures uniqueness." (see https://www.rfc-editor.org/rfc/rfc4287#section-4.2.6). Using the slug of the event together with its date should be sufficiently unique.

**Comment by ishar19** [comment]
> Hey @ishar19, this looks awesome! ✨
> 
> Here's some things to consider to make this useful for posting updates to social media, and to be useful in RSS readers:
> 
> * the start date of the event should be included in its title
> * instead of using the summary element to hold the location, I would instead use the content element to render the same information that is listed on the event card. Summary element can be omitted.
> * we cannot use the URL to the actual event as atom:id: "The content of an atom:id element MUST be created in a way that assures uniqueness." (see https://www.rfc-editor.org/rfc/rfc4287#section-4.2.6). Using the slug of the event together with its date should be sufficiently unique.

Hey @sabine thanks for the review and insights and recommended changes, let me make those and get back to this 
Thanks!

**Comment by ishar19** [comment]
so sorry for delay, i was out for a gateway, will try to wrap this up by 2-3 days

**Comment by ishar19** [comment]
hey @sabine i have updated the format, please take a look. Thanks 
image

**Comment by cuihtlauac** [comment]
We've just merged a PR #2461 which contains generic RSS feed creation logic that could be used here.

**Comment by ishar19** [comment]
> We've just merged a PR #2461 which contains generic RSS feed creation logic that could be used here.

just saw it, looks really nice, shall i refactor this to use that logic?

**Comment by sabine** [comment]
Ah yes, that would be awesome!

**Comment by ishar19** [comment]
> Ah yes, that would be awesome!

sure thing, will do that ASAP @sabine , thanks for the heads up!

**Comment by ishar19** [comment]
Closing this one with link to new PR #2495

**Pull request closed without merging**
