### PR TITLE
Use Ocamlorg_static.Media.url for media

### LINKED ISSUE #1147: Serve data/media files under digest URLs
Similar to https://github.com/ocaml/ocaml.org/issues/1049, we should also serve the files from `data/media` (see [`Ocamlorg_static.Media`](https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_static/ocamlorg_static.ml)) under digest URLs. 

This requires adding a `url` function to `Ocamlorg_static.Media`, similar to [the `url` function of `Ocamlorg_static.Asset`](https://github.com/ocaml/ocaml.org/blob/384684f5b59a40ae71b07a8bb90cb0180977ff3f/src/ocamlorg_static/ocamlorg_static.ml#L14).

Apart from that we need to go through all the images in the templates and use the new function where appropriate (in the same way as https://github.com/ocaml/ocaml.org/pull/1145).

### PR DESCRIPTION
**Pull request by r17x**
Closes #1147

<hr/>

Hello @sabine , I have been make a PRs related with #1147 but not sure of my implementation is correct (*meet the expectation*).

Feel free for make a Review for this PRs

Thanks

### CODE REVIEW

**Comment by sabine** [comment]
Looks good to me. We also need to go through all the templates to see where media files are being used and then use the new function to render the digest-URL. Media is everything that lives in the `data/media` folder.

ETA: every kind of data in the `data/` folder has an associated module in `Data`, and some fields are paths of files in the `data/media` folder.

One type of media files that we won't be able to serve under digest URLs are the ones which are referenced from within the body of a markdown (`.md`) file because there's no way to render them.

**Comment by r17x** [comment]
Hello @sabine 👋

Sorry for my late updates. 

I have been resolved conflicts after main branch updated and implemented Ocamlorg_static.Media.url in templates.

See the differences between this branch and ocaml.org (image attachments)

```diff
# in main branch or ocaml.org
-- /media/books/ocaml-scientific-computing.png
# in this branch after use Ocamlorg_static.Media.url
++ /media/_/OTg1ZWQ3NWMzZTZkYzVjNDRjN2VkY2FiNWJjNjEzMzk/books/ocaml-scientific-computing.png
```
image

**Review by sabine — APPROVED** [review]
Looks good to me! Thanks for the contribution!

This issue is great to be resolved because, now, organizations can update their logo and there will be no issues with users' browsers still caching an old version. :+1: 

Never worry about taking time... we intentionally choose these issues so they are not time critical. After all, this is open source, and it's super nice of you to contribute! From our side, the goal is to provide a space where we can learn from each other and collaborate while making OCaml.org as useful to the community as we all can. :slightly_smiling_face:

**Comment by r17x** [comment]
> the goal is to provide a space where we can learn from each other and collaborate while making OCaml.org as useful to the community as we all can. 🙂
@sabine 

The aspect of providing space for collaboration and learn from each other is an interesting in the OCaml community.

Thanks for providing the space.

**Review by cuihtlauac — APPROVED** [review]

**Pull request merged**
