### PR TITLE
Learn Guidelines: recommend ocamlformat, remove formatting text

### PR DESCRIPTION
**Pull request by mndrix**
This pull request implements the proposal discussed in #240. I thought it might be easier to discuss something concrete.  The important changes are in the first commit.  The others are minor improvements that I encountered while re-reading the article.

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks for getting the ball rolling on this @mndrix 🙂 

While I agree that there's some duplication with what ocamlformat does, I still think there's value in having a set of formatting guidelines on the site for two reasons:

- Not everyone uses a formatter, so having guidelines may help people who don't use ocamlformat or other formatters to align themselves to the community's practices if they want to
- Even if the formatting is automated, it's still nice to know the reason formatters do what they do.

So instead of removing these completely, I'd recommend either putting the formatting guidelines in a subsection, mentioning that this is automated when using ocamlformat with the default profile, or providing a separate document, which maybe could include more information about ocamlformat.

**Comment by mndrix** [comment]
> * Not everyone uses a formatter

Thanks for the reminder.  I've been auto-formatting my code for so long that I forget that some prefer to do it manually. :-)

> I'd recommend either putting the formatting guidelines in a subsection

This seems sensible. I don't see a need for a second document.  I'll plan to update this pull request by moving all the formatting recommendations to a section at the bottom and include a pointer to ocamlformat.

**Comment by mndrix** [comment]
I've updated the pull request to de-emphasize manual formatting guidelines by moving them to their own section at the bottom of the Guidelines document. @tmattio, let me know if you want other changes.

**Comment by tmattio** [comment]
Thanks @mndrix, this looks good!

Unrelated to the goal of this PR, but I find the page very hard to read. There are so many titles, huge chunks of text in quotes, nested quotes (?!). The page could use some further readability improvements I think. That's outside of the scope of this PR though, so merging now 🙂

**Pull request merged**
