### PR TITLE
better header package search box styles

### PR DESCRIPTION
**Pull request by sabine**
|before|after|
|-|-|
|Screenshot 2023-01-20 at 15-16-30 Learn OCaml|Screenshot 2023-01-20 at 15-16-27 Learn OCaml|

Thanks go to Claire for suggesting and mocking up this input+sidebutton!

### CODE REVIEW

**Review by cuihtlauac — APPROVED** [review]

**Comment by cuihtlauac** [comment]
I clicked on the wrong button so many times!

**Comment by sabine** [comment]
I assure you, you are not the only one. :grin:

**Comment by cuihtlauac** [comment]
BTW: I'm not a great fan of that "Get Started" button.

**Comment by sabine** [comment]
We are going to de-emphasize "Get started" next, and propose to hide it on pages where it is not relevant. (Claire also suggested that.)

**Comment by tmattio** [comment]
Minor UI suggestion: would it make sense to keep the placeholder grey (instead of orange)? I think it's a bit unusual to have colour on the placeholder.

**Pull request merged**
