### PR TITLE
Add OCaml 5.0.0~beta2 announce to the news

### LINKED ISSUE #644: Add OCaml 5.0.0 second beta release news
I was looking for the announcement of the second beta release on the website and didn't find it. It's on the discuss forum, though.

https://discuss.ocaml.org/t/ocaml-5-0-0-second-beta-release/10871

### PR DESCRIPTION
**Pull request by cuihtlauac**
Copied & translated into markdown @Octachron announce: 

https://discuss.ocaml.org/t/ocaml-5-0-0-second-beta-release/10871

Processed issue links using:
```
sed -i 's/#\([1-9][0-9]*\)/[#\1](https:\/\/github.com\/ocaml\/ocaml\/issues\/\1)/g'
```

Fix: https://github.com/ocaml/ocaml.org/issues/644

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks @cuihtlauac!

FYI, you can get the raw content of the Discuss posts in markdown with `https://discuss.ocaml.org/raw/<post id>`. So for instance the content of this post is at https://discuss.ocaml.org/raw/10871

**Comment by tmattio** [comment]
Should we change the color of the announcement banner? People will probably not notice the change (and miss the announcement if they are not on Discuss) if the color stays the same

**Comment by cuihtlauac** [comment]
Holidays season colors? Forest green and red? Some snowflakes? :smile:

**Comment by Octachron** [comment]
I didn't think of sending my announce to ocaml.org, sorry!
Note that I think it could also make sense to have one announce for all the beta releases, and another for the future release candidate(s).

**Comment by tmattio** [comment]
Now I'm wondering which colour we'll want to use for the final release, green looks nice 😅 
Maybe we want to keep the colour change for the final release only?

**Comment by cuihtlauac** [comment]
I'm confident we'll find yet another nice colour for the final announcement, there's so many of them. Today we like green, let's move forward in green.

**Review by tmattio — APPROVED** [review]

**Pull request merged**
