### PR TITLE
No crunching (fixed)

### PR DESCRIPTION
**Pull request by gpetiot**
Build on top of #958 (reverts d1c193f) and #1167

The fix is in cf0bece, there was a wrong url in `src/ocamlorg_frontend/pages/package_documentation_not_found.eml`

Edit: Everything works fine locally, waiting for CI

### CODE REVIEW

**Comment by cuihtlauac** [comment]
Thanks, @gpetiot, for finding out what went wrong with #958.

By my tests, it is indeed fixed and faster, around 40%. Not a surprise; compilation is an IO-bound task.

I should have expressed my concerns about this patch during the first PR review. I'm sorry I did not.

How can we measure the impact on operation performance? It looks like a tradeoff; we win at compile time but lose on latency. I don't feel comfortable merging without some data on the latter impact.

Also, I'm cautious about changing a design *only* for compilation performance reasons. To me, compilation speed-up should primarily come from faster hardware, build set-up improvements or code cleaning.

The existing design is fast and simple, qualities which are hard to achieve simultaneously. This is done at the expanse of compilation time and memory consumption. I'm not sure tipping that balance is worth the workload.

**Comment by sabine** [comment]
The next step here would be to serve the assets via a CDN to increase performance for people sitting in remote locations across the world.

ETA: but indeed, it may not yet be the right time for this and it all needs to be done at the same time in order to avoid a regression.

**Comment by gpetiot** [comment]
Should I close this PR?

**Comment by sabine** [comment]
Ok, so the situation with this is:

1. Its true usefulness will only unfold at the point where we either (a) run out of memory for the assets (this is many years in the future) or (b) serve assets from CDN in different geographic locations. As long as neither these happens, the benefit doesn't justify the complexity.
2. Only when we have another caching mechanism for serving the assets will this not cause a performance regression at runtime.

So yes, let's close it for now.

**Pull request closed without merging**
