### PR TITLE
OCaml 5.1.1 release

### PR DESCRIPTION
**Pull request by Octachron**
This PR adds the release and the changelog entry for OCaml 5.1.1 (whose release should be officially tomorrow Paris time).

### CODE REVIEW

**Review by christinerose — APPROVED** [review]

**Comment by Octachron** [comment]
I will be moving around one paragraph and the changes entries. Would you prefer that I do so after your line editings?

**Comment by christinerose** [comment]
> I will be moving around one paragraph and the changes entries. Would you prefer that I do so after your line editings?

All finished with line editing. It shouldn't affect anything, but I'll have another quick review when you're finished. 🙂

**Comment by Octachron** [comment]
Done (and the changelog parsing should be fixed now).

**Review by christinerose — APPROVED** [review]

**Comment by christinerose** [comment]
Looks great @Octachron!

**Pull request merged**
