### PR TITLE
Add Pagination to the Changelog Page

### LINKED ISSUE #1561: Add Pagination to the Changelog
# Task

Currently, all the entries of the changelog are displayed on a single HTML page at https://ocaml.org/changelog.

Since there are a lot of entries, it makes sense to add pagination:
Screenshot 2023-10-03 at 15-13-43 OCaml Blog

As an example of how to do pagination (and for possible code sharing), look at how it is done for the Blog:
1. In `handler.ml`, the list of entries is paginated according to a query parameter "p" from the URL: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/src/ocamlorg_web/lib/handler.ml#L191-L218
2. In the template, the pagination component is rendered: https://github.com/ocaml/ocaml.org/blob/6a36190efe178a6236a13e4cd79adbf9b42e10c6/src/ocamlorg_frontend/pages/blog.eml#L67

--

What you need to do:

1. modify the function `changelog` in `handler.ml` to paginate the list of changelog entries.
2. render the pagination component in `changelog.eml`

(Related to https://github.com/ocaml/ocaml.org/issues/1125.)

### PR DESCRIPTION
**Pull request by m-spitfire**
closes #1561

I kept 10 items per page.

Here's how it looks now:
Screenshot 2023-11-10 at 2 18 05 AM

### CODE REVIEW

**Review by sabine — COMMENTED** [review]
Looks pretty great already, just one minor nitpick and one actual concern:

1. Show more items, maybe 30 per page.
2. When a tag is selected, we have to consider that in the pagination hrefs as well. https://github.com/ocaml/ocaml.org/pull/1657/commits/34bcd238a9bb97f0ca236efe70f126457a708860 faced the same problem and introduced the function `paginated_href` to accomodate the `q=` query param. `paginated_href` could be generalized to handle arbitrary query params.

**Comment by tmattio** [comment]
Is loading the page an issue (in that it's become too large)? If not, I'm wondering if an infinite scroll would be a better alternative to pagination for the Changelog. What do you think?

**Comment by sabine** [comment]
@tmattio infinite scroll is a prettier solution in general if done well, but I think it should be another task to transform all the paginations to infinite scroll at the same time. This is a thing where HTMX would likely do well.

Yes, the page is pretty heavy.

**Comment by tmattio** [comment]
> @tmattio infinite scroll is a prettier solution in general if done well, but I think it should be another task to transform all the paginations to infinite scroll at the same time. This is a thing where HTMX would likely do well.

Pagination made more sense to me for the other pages of the site, whereas with the changelog being a timeline, it makes it a better candidate than other paginated content in my mind. But if you prefer implementing pagination first and changing that to infinite scrolling later, that's ok too.

> Yes, the page is pretty heavy.

Can you share numbers (size and time to load)? The page usually loads fast enough for me that I never paid attention to the fact that it was larger than usual. Having everything in one page was also convenient at times, so just to understand how we're improving UX with the pagination

**Comment by m-spitfire** [comment]
@sabine I addressed the issues you mentioned. I'm not sure if I love how I named the search params variable `queries`, looking forward to your review.

Also current implementation assumes that there will be no parameter with the "key" `p`, but I don't think that's a problem.

**Review by sabine — APPROVED** [review]
Looks good to me. I have no qualms with the name `queries` - it makes clear that there's a list of query params.

I also agree that assuming that there's no query param `p` is fine.

Thanks for the contribution @m-spitfire! :+1:

**Pull request merged**
