### PR TITLE
Adding more libraries to playground

### PR DESCRIPTION
**Pull request by nikochiko**
I am attempting to add a library to the playground - https://github.com/Sudha247/ocaml-joy - so that I can provide an editor and an SVG rendering side by side (I am doing it with a REPL-toplevel here - https://kaustubh.page/joy.ml/).

I need some help with doing this - I can then document the procedure that works.

I am able to load the cmi and the cma.js, but I get a JavaScript `TypeError` now when I try to do `Joy.init_svg "pane-1"`
image

Note: this is the branch of Joy that needs to be pinned for this to work: https://github.com/Sudha247/ocaml-joy/tree/svg

### CODE REVIEW

**Comment by nikochiko** [comment]
Now I think this might be an issue with Js_of_ocaml actually - other methods seem to work.

**Comment by nikochiko** [comment]
Perhaps because it is trying to manipulate the DOM from a web worker.

**Comment by sabine** [comment]
Hey @nikochiko! Sorry, this got lost under all the Outreachy PRs.

Thanks for taking the time to try this. I remember @gpetiot made an attempt at loading packages into the playground also. It would be great if he can comment on this. Also @jonludlam might have a few pointers.

**Comment by tmattio** [comment]
Closing this as it seems stalled. Thank you for the PR @nikochiko don't hesitate to pick this up again if you'd like.

I know there's been some exploration to generate build artifacts of the opam packages in the Docs pipeline for consumption from the playground. Maybe one day we'll be able to use any JS-compatible opam package from the playground!

**Pull request closed without merging**
