### PR TITLE
add initial server-side code-highlighting

### PR DESCRIPTION
**Pull request by patricoferris**
This PR adds some static code-highlighting (i.e. not done on the client-side with highlight.js or prism.js) as part of #105. The library (`hilite`) reuses the textmate grammars from vscode with some minor modifications because the textmate library wasn't happy parsing them. 

The colours are of course chosen pretty randomly and I'm happy for anyone to change them. One small issue is most OCaml blocks are formatted like a top-level, we will need some additional logic (hopefully not in this PR) to un-highlight the output, this is especially problematic for compiler errors (see image 3).

**Image 1 - Toplevel OCaml that looks okay (does leak into function type)**

Screenshot 2021-09-22 at 16 32 13

**Image 2 - Dune file highlighted**

Screenshot 2021-09-22 at 16 32 40

**Image 3 - Toplevel looks a bit odd**

Screenshot 2021-09-22 at 16 44 58

### CODE REVIEW

**Review by tmattio — APPROVED** [review]
I'm really impressed by the footprint of the library: i.e. a single call to `Hilite.Md.transform`!

I didn't review the actual library, but everything else LGTM. I would maybe inline the CSS code for the syntax to avoid another roundtrip, but that's a detail.

Feel free to merge whenever the tests are passing 🎉

**Comment by patricoferris** [comment]
Thanks for the review :)) What's the best way to pull in the one dependency of `Hilite` that doesn't belong to any of the opam files in the repo? I've added it to the `Makefile` as a dev dependency but we don't install this in CI ?

**Comment by tmattio** [comment]
> Thanks for the review :)) What's the best way to pull in the one dependency of Hilite that doesn't belong to any of the opam files in the repo? I've added it to the Makefile as a dev dependency but we don't install this in CI ?

Ah, right, the tests will try to run everything under `src/`. A quick workaround would be to move `hilite` to `tool/` or `vendor/`.

If we do want to run the tests in the CI, I'd suggest installing Hilite's deps in the CI step with a comment, and we'll remove the step once it's released.

**Comment by tmattio** [comment]
Or we can create a package `hilite` if you prefer.

**Comment by patricoferris** [comment]
Thanks!

**Pull request merged**
