### PR TITLE
implement resources card and component

### LINKED ISSUE #2114: Implement "Resources" Card Components and Section for use on Learn Overview Page
We have a design for a "Resources" section that has cards to external resources.

Your quest, if you choose to accept it is to implement this component so it can be used in one or more places on the pages.

Screenshot from 2024-02-28 22-09-43

[Figma design](https://www.figma.com/file/eh8gAxaxrZT6RG3psHCm6M/Dark-%26-Light-mode-pages?type=design&node-id=1186%3A986&mode=dev)

Relevant external resources to link to:
* https://sherlocode.com/ (packages page)
* https://doc.sherlocode.com/ (packages page)
* https://github.com/ocaml-community/awesome-ocaml (learn overview)
* http://ocamlverse.net/ (learn overview)
* https://github.com/ocaml/ocaml.org/issues/2041 (learn overview)

A suitable image would need to be chosen/created based on the resource linked to.

### PR DESCRIPTION
**Pull request by ghost**
Resolves #2114

Screenshot 2024-04-09 at 14-11-25 The OCaml Community

### CODE REVIEW

**Comment by ghost** [comment]
@cuihtlauac @SaySayo @sabine 
Please review

**Comment by sabine** [comment]
Hey @amarachigoodness74, that looks like a really nice start! :+1: :sparkles: 

In the meantime, we have better images for the cards on Figma here:

https://www.figma.com/file/7hmoWkQP9PgLTfZCqiZMWa/OCaml-Community-Pages?type=design&node-id=152%3A386&mode=dev&t=kePoh4Cvcc35Nemo-1

It should be possible to export images from Figma to use them for the cards.

**Comment by ghost** [comment]
@sabine I just updated. Please review. Thank you

**Review by sabine — APPROVED** [review]
Hey @amarachigoodness74 thanks for bearing with me, I added some images from a newer Figma design and this is merging now! :sparkles: :heart:

**Comment by yurug** [comment]
That's great! Thank you very much! @amarachigoodness74 and @sabine 

There is just one typo in the URL for LearnOCaml, as
```
https://github.com/ocaml/ocaml.org/issues/2041
```
should probably be replaced with
```
https://github.com/ocaml-sf/learn-ocaml 
```
See https://github.com/ocaml/ocaml.org/pull/2331

**Comment by cuihtlauac** [comment]
@yurug

Is this ok? https://github.com/ocaml/ocaml.org/pull/2332

**Pull request merged**
