### PR TITLE
Update code highlighting color scheme

### LINKED ISSUE #1772: Better Code Highlighting Color Scheme Showdown
# Task

The color scheme for the code highlighting in the code blocks in the OCaml.org Learn area could be better.

The current color scheme is this:

Screenshot 2023-11-15 at 21-05-20 Transitioning to Multicore with TSan · OCaml Tutorials
(https://ocaml.org/docs/multicore-transition)

```
span[class*="keyword"] {
  color: #fede5d;
}

span[class*="constant"] {
  color: #fabd2f;
}

span[class*="function-binding"] {
  color: #36f9f6;
}

span[class*="variable"] {
  color: #85ebeb;
  font-style: italic;
}

span[class*="support"] {
  color: #83a598;
}

span[class*="comment"] {
  font-style: italic;
}

span[class*="literal"] {
  color: #d3869b;
}

span[class*="string"] {
  color: #b8bb26;
}

span[class*="numeric"] {
  color: #ff5683;
}
```

Respond with a new color scheme. Color scheme must meet WCAG contrast requirements. (Use a WCAG checker, e.g. https://webaim.org/resources/contrastchecker/ to check.)

When we have more than one submission, let's do an elimination game where the different color schemes face off against each other: People vote to determine the better option in rounds of pairs of two until a single champion emerges.

For the showdown, we need one code block that exhibits all the different highlight colors. I haven't checked if the code block in question here has all of the colors. If it doesn't, we need another code block to show off everything.

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Updates the code highlighting color scheme to a new set of colors based on community voting (https://github.com/ocaml/ocaml.org/issues/1772#issuecomment-1813439004) and WCAG contrast requirements.

- Changes color values for `keyword`, `constant`, `function-binding`, `variable`, `support`, `comment`, `literal`, `string`, and `numeric` classes to new, WCAG-compliant colors.
- Maintains the existing diff-related styles without changes.
- Refer to [stephango.com/flexoki](https://stephango.com/flexoki) for color styles.

fixes https://github.com/ocaml/ocaml.org/issues/1772

### CODE REVIEW

**Review by cuihtlauac — APPROVED** [review]
Thanks @Siddhant-K-code, that looks good to me.

**Comment by cuihtlauac** [comment]
@Siddhant-K-code Don't worry about the failed test, that's not on you. It doesn't matter. It's there because it was in main when you created your branch. You can rebase to make it go, but it's not required.

**Comment by Siddhant-K-code** [comment]
I've rebased it with the latest changes in `main`, hope it should be fine now to merge 🤞🏼

**Review by cuihtlauac — APPROVED** [review]
Let's merge this

**Pull request merged**
