### PR TITLE
removed packages-home.png

### LINKED ISSUE #1890: Hide "OCaml Packages" Image on Homepage on Mobile View
Dear maintainers,
First of all, thanks for your hard work on making the OCaml ecosystem available for everyone 
👐

This issue is just to point out that there is a display problem with the image bellow the OCaml Package Explore link. The image appears to be right shift.

Here is two screenshots to show the issue on both Chromium and Firefox mobile :

Hope it helps 😇

### PR DESCRIPTION
**Pull request by The-Amoghavarsha**
Closes #1890

Have also removed the source image at `ocaml.org/asset/img/home/packages-home.png`. One orphan down 🫡

### CODE REVIEW

**Review by sabine — APPROVED** [review]
Thanks @The-Amoghavarsha! :fire: :sparkles:

I adjusted the padding of the parent container and this looks much nicer than this odd screenshot of the packages page!

**Comment by The-Amoghavarsha** [comment]
> Thanks @The-Amoghavarsha! 🔥 ✨
> 
> I adjusted the padding of the parent container and this looks much nicer than this odd screenshot of the packages page!

You read my mind. I'm glad you did that. I was about to ask you that. :laughing: Was also contemplating on the idea of centering `OCaml Packages` to the centre in web view, as there's nothing on the right side. Adding something could also fill the void.

Another crazy idea is to introduce the following section in the centre. And below that, we can route to the `packages` page by naming it `explore more` (or something similar) and we can make the `packages` page more colorful. :art: 

image

They are all just ideas :man_shrugging:

**Comment by sabine** [comment]
I figured since this entire page is due for redesign in Q1 anyways, we just merge. :slightly_smiling_face:

**Comment by The-Amoghavarsha** [comment]
I see. While I'll be in the (do)loop for that (if possible). :smile_cat:

**Pull request merged**
