### PR TITLE
fix matrix link

### PR DESCRIPTION
**Pull request by redianthus**
cc @sabine

This is the real matrix room that has been here for years, with 200+ members...

### CODE REVIEW

**Comment by talex5** [comment]
Hmm, is this space official? It only has 2 members (including me; I just joined!). The one on roscidus.com has 42 members. Can we merge them somehow?

**Comment by tmattio** [comment]
Indeed, let's merge the servers somehow before we replace the existing Matrix server with this new one. Closing the PR in the meantime, but don't hesitate to re-open when we're ready to update the Matrix link.

**Comment by redianthus** [comment]
I don't understand. There's a room and a space on matrix.org, with 200+ members and 30+ members for the space. The room has been here for years. Why do you choose to link to roscidus.com ? We don't know who is running this server and why we should trust in in any way. Compared to the well established room and trusted server matrix.org. This makes no sense to me.

**Comment by tmattio** [comment]
I'm not a Matrix user myself and have only ever heard of the spaces on roscidus.com. I'm happy to link to matrix.com if this is indeed the most established server. Could you answer @talex5's question above:

> Hmm, is this space official? It only has 2 members (including me; I just joined!). The one on roscidus.com has 42 members. Can we merge them somehow?

**Comment by talex5** [comment]
> Why do you choose to link to roscidus.com ? We don't know who is running this server and why we should trust in in any way. Compared to the well established room and trusted server matrix.org. 

Matrix is distributed, so it doesn't matter what server something runs on. Each server that chooses to participate keeps a copy of the room history, and any servers can join, trusted or not.

I run roscidus.com, which provides one entry-point to the space, and @avsm provides another at `#ocaml:recoil.org`. The web-site can use either address, and there's no problem adding further addresses on other servers if you don't trust either of these servers.

The OCaml room having 200+ members is irrelevant, since both spaces are linking to that room anyway.

**Comment by redianthus** [comment]
It matters if in two years you stop doing OCaml and decide not to run this server anymore... Otherwise, you can be sure the OCaml room would have been on my server at #ocaml:saucisseroyale.cc ("royal sausage" for the non french speakers). 

It also matters because once again, it's Tarides who decides which room are allowed in the space. The OCaml room and space have admins that are in different companies/uni and it had since the beginning.

Also, I believe spaces to be quite unused, most client don't support them yet. I'm on ~100 rooms and no space (except the OCaml one). What people use and expect to find is a room. @avsm has been ignoring the matrix room for years, systematically [not linking to it](https://discuss.ocaml.org/t/ocaml-org-recapping-2022-and-queries-on-the-fediverse/11099) (ofc he doesn't forget to provide link to the recoil/roscidus ones :laughing:), my favorite one is [here](https://github.com/ocaml/ocaml.org/issues/767) where @Swrup is completly ignored. I understand that linking to a space you own is a good way to keep ignoring it.

**Comment by avsm** [comment]
Please try to use this forum to find consensus amongst each other, and to take a positive view of each other's actions where possible. Rather than 'systematically ignore', I can indicate that I had no idea that the room existed as it was posted as a driveby aside in a very long thread. I don't habitually use any synchronous large chat channels myself, so I'm happy to be corrected.

I suggest:

- the oldest and biggest OCaml room should indeed be the one linked to.  Spaces are new (and still rather experimental), so just linking to the room seems like a good default.  The space can also be linked to as optional.
- if in doubt about which of two spaces to use, why not merge them?  Even if not technically possible for spaces, the admin teams can join forces and decide on which one is used going forward.  The main thing to decide are the grounds for acceptance and modifiction; if it's going to be used on ocaml.org, then the OCaml Code of Conduct is the appropriate manifest to adopt.
- once consensus is achieved and there's one main room and one main space, we can investigate running a Matrix server on ocaml.org to act as the main host, rather than matrix.org. I'm a little reluctant to commit to this since Synapse has quite a high operational overhead (in terms of keeping the database vacuumed and manageable), but it would be cool to have a room under the OCaml domain! Perhaps Conduit or one of the other servers are easier to operate if there is no need for active user registration, and just room hosting.

**Comment by talex5** [comment]
Spaces can be nested, so I've just linked to the one on matrix.org from the one on the web-site. It's a little confusing though, with so many things named "ocaml"!

Note that an address on matrix.org isn't necessarily more trustworthy than one on a private server, since anyone can create addresses on matrix.org.

I don't have any wish to control the OCaml Matrix space; it's only there because I wasn't aware of any pre-existing one. However, the one I created has more members, so it's less disruptive to continue using that as the main one (whatever server we use as the entry-point to it; ocaml.org would be ideal, indeed).

> my favorite one is https://github.com/ocaml/ocaml.org/issues/767 where @Swrup is completly ignored.

@Swrup: you posted a link to the room `#ocaml-language:matrix.org`, which was linked to from the space that Anil posted. Were you asking for something to be changed about the PR?

**Comment by redianthus** [comment]
> I can indicate that I had no idea that the room existed

@avsm, I'm starting to wonder if someone else is pretending to be you ! You've been in this room since 2021 and we even discussed about your PinePhone... ?

> Spaces are new (and still rather experimental), so just linking to the room seems like a good default. The space can also be linked to as optional.

I agree. I updated the PR.

**Comment by swrup** [comment]
Hello,

> @Swrup: you posted a link to the room #ocaml-language:matrix.org, which was linked to from the space that Anil posted. Were you asking for something to be changed about the PR?

I just wanted to make sure everyone is aware of this room (clearly the main ocaml related room on matrix)

> Spaces are new (and still rather experimental), so just linking to the room seems like a good default.

I agree too.
I'm still confused about space and do not comprehend why it exists.

> Why do you choose to link to roscidus.com ? We don't know who is running this server and why we should trust in in any way. Compared to the well established room and trusted server matrix.org.

Thank you for hosting a matrix server!
In a federated spirit I think it is nice and not an issue to link to a server hosted by a community member instead of the go to matrix.org one.

But...

> It matters if in two years you stop doing OCaml and decide not to run this server anymore...

...is a valid concern.

> Matrix is distributed, so it doesn't matter what server something runs on. Each server that chooses to participate keeps a copy of the room history, and any servers can join, trusted or not.

Can a room still live on if the server it was made on is offline?
I don't think it does.

I think this PR should be merged because #ocaml-language:matrix.org is the more popular room for sure and is very trust worthy.
And it has a good administration team:
- they are passionate ocaml and matrix people
- it seems they come from various company/university (it looks important for @zapashcanon that no one monopolize the community)
- there was never a moderation issue

> we can investigate running a Matrix server on ocaml.org to act as the main host, rather than matrix.org

It could be nice to host a server for the ocaml community.
But it is also nice to let the community do its thing, let it grow and live freely without being confined to a foundation.
Should ocaml.org run a lemmy/mobilizon/mastodon/irc server too?

On a side note I feel it is important that the #ocaml-language:matrix.org room stay unofficial and informal.
So people are not afraid to come join in with their funny cat avatar to talk, ask question and have fun.

**Comment by talex5** [comment]
> > Matrix is distributed, so it doesn't matter what server something runs on. Each server that chooses to participate keeps a copy of the room history, and any servers can join, trusted or not.

> Can a room still live on if the server it was made on is offline? I don't think it does.

I'm not an expert on Matrix, but I thought this was the whole point of the protocol (it's wildly over-complicated if not!). [The specs](https://spec.matrix.org/latest/) say:

> Room data is replicated across all of the homeservers whose users are participating in a given room. As such, no single homeserver has control or ownership over a given room. [...] Matrix optimises for the Availability and Partitioned properties of CAP theorem at the expense of Consistency.

My understanding is that I can turn roscidus.com off without affecting anyone using any rooms or spaces created there - no one will even notice. However, the joining link on the web-site would stop working, and would then need to be updated to point at another server with a replica of the space.

**Comment by sabine** [comment]
> My understanding is that I can turn roscidus.com off without affecting anyone using any rooms or spaces created there - no one will even notice. However, the joining link on the web-site would stop working, and would then need to be updated to point at another server with a replica of the space.

I am not sure this is correct. The **rooms** will still exist because they are federated, but is the **space** federated, too? When I dug around I could not find a definite answer on whether the space is dissolved when a server is decommissioned.

**Comment by talex5** [comment]
> I am not sure this is correct. The rooms will still exist because they are federated, but is the space federated, too? When I dug around I could not find a definite answer on whether the space is dissolved when a server is decommissioned.

The [proposal for Matrix "spaces"](https://github.com/matrix-org/matrix-spec-proposals/blob/97737596e70917b511e8dfbeda5df8235b6cc2e2/proposals/1772-groups-as-rooms.md#proposal-for-matrix-spaces-formerly-known-as-groups-as-rooms-take-2) says:

> Each space is represented by its own room, known as a "space-room". The rooms within the space are determined by state events within the space-room. Space-rooms are distinguished from regular messaging rooms by the presence of a 'type': 'm.space' property in the content of the m.room.create event.

**Comment by redianthus** [comment]
@tmattio, could we merge this ?

**Comment by sabine** [comment]
@zapashcanon can we merge the cards into a single one, like with Mastodon? (see here: https://github.com/sabine/ocaml.org/tree/merge_matrix_cards)

**Comment by redianthus** [comment]
@sabine, I added your commit. Thanks so much for writing the code, I'm so bad with this kind of stuff...it would have taken me forever.

**Pull request merged**
