### PR TITLE
commit

### PR DESCRIPTION
**Pull request by Solar-Rays**
Making a demo pull request to submit my initial application with Outreachy while I continue to work on the task.

### CODE REVIEW

**Comment by sabine** [comment]
@Solar-Rays I'm assuming this is related to https://github.com/ocaml/ocaml.org/issues/1651? If there's any help needed, please do reach out in #outreachy channel in Discord.

**Comment by Solar-Rays** [comment]
@sabine Yes it is related to that issue. I have been on it all this while and debugging the issue has proved more complicated than I had thought. I am collaborating with someone on the Outreachy internship to figure it out though.

**Comment by sabine** [comment]
Closing this PR because the corresponding issue seems to have been resolved by #1722

**Comment by Solar-Rays** [comment]
Hi @sabine This does not seem to be fixed yet. Please check the Winter 2021 section of the ocaml.org/outreachy page on mobile.

**Pull request closed without merging**
