### PR TITLE
Minor improvements to the home page, improved text

### PR DESCRIPTION
**Pull request by sabine**
* adds missing heading tags for improved semantic HTML - improves accessibility
* improvements to the texts, reordered feature sections to better reflect OCaml's values and priorities: Safety + Simplicity = Reliability, Editor and Tooling = Productivity, Fast compiler + Efficient Applications = Performance
* improved header section: bigger subtitle, clearer title and added latest release link (as requested by community feedbacks)
* improved accessibility of code example: added prompts and aria-label to announce responses from the OCaml REPL

|before|after|
|-|-|
|Screenshot 2023-03-02 at 18-16-21 Welcome to a World of OCaml|Screenshot 2023-03-21 at 09-24-16 Welcome to a World of OCaml|
|Screenshot 2023-03-02 at 18-18-07 Welcome to a World of OCaml BE SAFE in first position|Screenshot 2023-03-02 at 18-18-11 Welcome to a World of OCaml RELIABILITY in first position|
|Screenshot 2023-03-02 at 18-18-52 Welcome to a World of OCaml WORK JOYFULLY in third position|Screenshot 2023-03-02 at 18-18-58 Welcome to a World of OCaml PRODUCTIVITY in second position|
|Screenshot 2023-03-21 at 09-30-03 Welcome to a World of OCaml BUILD FASTER in second position|Screenshot 2023-03-21 at 09-29-53 Welcome to a World of OCaml PERFORMANCE in third position|
|nothing|Screenshot 2023-03-21 at 09-25-16 Welcome to a World of OCaml a budding testimonials block with citations|

### CODE REVIEW

**Comment by sabine** [comment]
I'm tempted to go even shorter on the hero section:
Screenshot 2023-03-02 at 18-30-07 Welcome to a World of OCaml

**Comment by cuihtlauac** [comment]
When V3 went online, I was a bit surprised by the style of the home page wording; it felt over-emphatic. I prefer your wording. However, the existing wording also felt opinionated. What was the context which led to the present text? I wish I knew a little bit more before changing it.

**Review by cuihtlauac — COMMENTED** [review]
When V3 went online, I was a bit surprised by the style of the home page wording; it felt over-emphatic. I prefer your wording. However, the existing wording also felt opinionated. What was the context which led to the present text? I wish I knew a little bit more before changing it.

**Comment by sabine** [comment]
Writing copy is an iterative process. The task is to capture and express the nature of OCaml truthfully and in a way that entices the reader to try it.

When such texts make untrue promises, people are disappointed when they try the thing and find out that it does not have the described qualities. When copy is too generic, it does not stand out and communicate anything. Best things happen when copy is specific, includes proof for claims, and upholds the values that the product stands for.

I personally see OCaml quite close to Rust in the sense that the values are similar but in a completely different order: Rust favors performance over simplicity, resulting in a complex type system that allows you to safely manage memory yourself. OCaml values simplicity over performance which explains the choice of giving up a bit of performance in favor of a simpler type system and mental model where the garbage collector deals with memory management concerns.

**Comment by avsm** [comment]
I like all these changes, and the thinking that went into making them.  Just one other factor that might be worth weaving in is age: OCaml has been going strong since 1996, and has legendary robustness and reliability for a programming language.  I was reflecting recently on my [ICFP 2007 experience report](https://anil.recoil.org/papers/2010-icfp-xen.pdf) which said (Section 2.4.1):

> Despite all this testing, we have never had a single XenServer defect reported from internal testing or from the field that can be traced back to a bug in the OCaml runtime or compiler. (During development we did once find a minor compiler bug, triggered when compiling auto-generated OCaml code with many function arguments, but this was already fixed in the development branch by the time we reported it and so no interaction with the maintainers at INRIA was required.)

...and this has also been true in subsequent large deployments like Docker for Desktop (@djs55 may wish to chime in).  Thinking back over that, the only real "bug" found in the past few years was the lack of segfault detection in Mac M1, but that had also been fixed in the development version of the compiler and a simple upgrade fixed that issue.

We should bring out this particular aspect of OCaml somehow, as it's also an interesting differentiator from other (younger) languages.

**Comment by cuihtlauac** [comment]
I wish the home page would state more explicitly OCaml is primarily, and from its inception, a functional programming language to which many features were added and continues to be added. Mainstream languages such as C, Java or even PHP travel in the other direction, FP gets added to them. Together with robustness and reliability, this is a heritage to be proud of and to be raised high.

**Pull request merged**
