### PR TITLE
Fix typo in Flambda 2 paper title

### PR DESCRIPTION
**Pull request by RadioPotin**
Hi again,

Thank you for merging #1544 

I've only now noticed a small typo went over my head in the title of a talk I've added in that MR so here's a fix to it.

Thank you for your time.

### CODE REVIEW

**Comment by RadioPotin** [comment]
Also, I have found a link to a video of a talk I haven't added in the previous PR, namely, [this video](https://watch.ocaml.org/w/db6ed2c4-e940-4d5f-82ee-d3d20eb4ceb7) for the talk "Digodoc and Docs".

Would you rather I open a new PR or just add a commit to this PR ?

**Comment by christinerose** [comment]
Thanks for catching that typo! That was all me!!! 🤦‍♀️ 
I can add that link in now, @RadioPotin!

**Review by christinerose — COMMENTED** [review]
Added the link, @RadioPotin. Please check I put it in the right place with the correct formatting for it. I followed what the other listings had.

**Comment by RadioPotin** [comment]
LGTM ! Thank you for your work !

Kind regards,
Dario

**Comment by tmattio** [comment]
Thank you both!

**Pull request merged**
