### PR TITLE
[Closed] Turn exercise 010 into practice

### PR DESCRIPTION
**Pull request by divyankachaudhari**
Addresses #2178. 

`dune build --root .` works.

### CODE REVIEW

**Review by cuihtlauac — CHANGES_REQUESTED** [review]
Don't include files related to exercises 013 in this PR

**Comment by divyankachaudhari** [comment]
@cuihtlauac  They'll go away once I merge the 013 PR 😅

**Comment by cuihtlauac** [comment]
Sure. But it's better if you don't include them in the pr. Review is easier, nothing unrelated interfering

**Comment by divyankachaudhari** [comment]
Noted. I'm closing this because I can't figure out how to remove them. I'm creating another PR. Please refer to #2205

**Pull request closed without merging**
