### PR TITLE
Update ocaml/setup-ocaml to v3

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Review by cuihtlauac — APPROVED** [review]
Thanks @smorimoto. This looks good to me. Out of curiosity, what prompted you to propose this?

**Comment by smorimoto** [comment]
@cuihtlauac I'm the author of the action, and I'm not really interested in continuing to maintain v2, and since v3 we're using opam 2.2, which includes fundamental performance improvements, improvements around depext, and some improvements towards Native Windows support, there's no reason not to update.

**Comment by cuihtlauac** [comment]
I'm merging the changes on `debug-ci.yml` on a separate commit #2565 for testing.

**Comment by cuihtlauac** [comment]
Bad news: it doesn't work. Here is the log of a manual run of `debug-ci.yml`. That action's sole purpose is to provide a mean to test things before updating the “real” actions

https://github.com/ocaml/ocaml.org/actions/runs/9762586364

**Comment by cuihtlauac** [comment]
I've updated `debug-ci.yml` again (PR #2583). The issue mentioned previously was in that file, not related to `setup-ocaml@v3`. Once the conflict is resolved, we can merge.

**Comment by cuihtlauac** [comment]
Fix for conflicts in https://github.com/smorimoto/ocaml.org/pull/1

**Comment by smorimoto** [comment]
Thanks for the PR!

**Comment by smorimoto** [comment]
@cuihtlauac gentle ping

**Pull request merged**
