### PR TITLE
advance opam-repository to March 30, commit id 9cfac26185d76f082bfdbf6f92f8e1a5aacbc589

### PR DESCRIPTION
**Pull request by sabine**
Advance the opam-repository pin and resolve breaking changes in `hyper` and `mirage-crypto-rng-lwt` (see https://discuss.ocaml.org/t/mirage-crypto-rng-unix-initialize/11505/3).

### CODE REVIEW

**Comment by cuihtlauac** [comment]
I suggest we pick commit `c03ceac6872a8ff0ebed2c4fa28b0013fb1984e2` (from march 20) which is the latest in the current `ocaml/opam:alpine-3.17-ocaml-4.14` docker image. That would avoid having to `git fetch`, which will remove some networking from the docker build and save some time with an equivalent result.

Another option, would be to pick the release of ocaml 4.14.1 in the opam-repository log. That would allow the compiler to be the same in all builds.

**Comment by sabine** [comment]
`hyper` was released on March 29. :thinking:

**Comment by sabine** [comment]
Hm, I guess we can keep this around as a draft until we advance opam pin beyond 9cfac26185d76f082bfdbf6f92f8e1a5aacbc589.

**Comment by cuihtlauac** [comment]
That makes sense. It shouldn't take long, @mtelvers told me images are built weekly.

**Comment by sabine** [comment]
Closing in favor of https://github.com/ocaml/ocaml.org/pull/1079

**Pull request closed without merging**
